---
- name: Install nginx
  hosts: test
  user: centos
  become: yes
  become_method: sudo

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Install the ambari-server package
    package:
      name: ambari-server
      update_cache: yes
      state: latest
