---
- name: Install nginx
  hosts: test
  user: centos
  become: yes
  become_method: sudo

  tasks:
  - name: cloning repo
    command: git clone https://github.com/krishna-dahifale/ansible_tower_demo.git
  - name: Run ifbaric.py file
    command: python ansible_tower_demo/iFabric.py
   
 
